### ISSUE TITLE
clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by alphaaurigae** [satyam1990/recupero#1]
16.04 clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)

```
07:27 $ make 
clang -ggdb -o ./bin/recupero ./src/*.c -I./inc/ -std=c99
/usr/bin/ld: cannot open output file ./bin/recupero: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:6: recipe for target 'recupero' failed
make: *** [recupero] Error 1
✘-2 ~/recupero [master|✔] 
```

**Comment by satyam1990** [comment]
I have removed the useful source code as I need to restructure the application. Hence, there is no use of building it anyways. In case you require a working sample application to recover jpeg's in linux please drop a message, will try to include the useful code and build instructions.

**Comment by alphaaurigae** [comment]
Thx for the reply!

I was looking for apps to restore files without extension or txt extension containing information.
Why not make a dev branch instead of removing code? :)

**Comment by satyam1990** [comment]
Yes i messed it up little bit that time, don't know what i was thinking :(. You can make use of TestDisk linux application it is much much more advanced and will get you lost files of almost all type. Also it's free and the best i have seen so far.

**Comment by alphaaurigae** [comment]
THX ill look into it, however, maybe your code is useful for others, no such thing as bad code :)
